### ISSUE TITLE
Crafting a stick

### ISSUE THREAD

**Issue by GamebP** [quentin452/Catzmod1.7.10#3]
Sharpless recepie messes up the recepie. Or you have somenthing wrong.
![image](https://user-images.githubusercontent.com/88152063/226178926-bf46c816-39f6-406a-a83d-adc90f4e0a43.png)

**Comment by quentin452** [comment]
yes something wrong 🗡️

**Comment by GamebP** [comment]
fixe. 
[stickkode.txt](https://github.com/quentin452/Catzmod1.7.10/files/11011200/stickkode.txt)

**Comment by GamebP** [comment]
Still a issue to newest build 
![image](https://user-images.githubusercontent.com/88152063/226192455-8c1f5a07-fc6f-494b-adc1-f8bc99d0e8d2.png)
What a scam on cat gunpowder
![image](https://user-images.githubusercontent.com/88152063/226192471-9bcdfedd-85e3-4af0-876d-1ef675c5d629.png)
